version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - dbpostgres 
  dbpostgres:
    image: postgres:10
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: x
      POSTGRES_PASSWORD: x
      POSTGRES_DB: x
